server:
  port: 8100

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 60
  server:
    expected-client-renewal-interval-seconds: 30
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: true
    renewal-percent-threshold: 1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true

